"""create users table

Revision ID: 033813c8d150
Revises: 3e9d386d9761
Create Date: 2026-03-31 08:01:10.668071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033813c8d150'
down_revision: Union[str, Sequence[str], None] = '3e9d386d9761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###
