"""add reviews table

Revision ID: 1417c81b0ab4
Revises: 6c9168b20244
Create Date: 2026-03-30 23:08:28.242910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1417c81b0ab4'
down_revision: Union[str, Sequence[str], None] = '6c9168b20244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_name', sa.String(length=100), nullable=False))
    op.add_column('reviews', sa.Column('is_verified_customer', sa.Boolean(), nullable=True))
    op.alter_column('reviews', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reviews', 'is_verified_purchase')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_verified_purchase', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reviews', 'is_verified_customer')
    op.drop_column('reviews', 'user_name')
    # ### end Alembic commands ###
