"""add reviews table for trust system

Revision ID: 1ef000e01f96
Revises: 1417c81b0ab4
Create Date: 2026-03-30 23:13:55.729279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef000e01f96'
down_revision: Union[str, Sequence[str], None] = '1417c81b0ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_verified_purchase', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('owner_reply', sa.Text(), nullable=True))
    op.drop_constraint(op.f('reviews_business_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviews', 'is_verified_customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_verified_customer', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_business_id_fkey'), 'reviews', 'businesses', ['business_id'], ['id'])
    op.drop_column('reviews', 'owner_reply')
    op.drop_column('reviews', 'is_verified_purchase')
    # ### end Alembic commands ###
