"""fix cities foreign key

Revision ID: 2e7226290fd8
Revises: 20273ec1e1d3
Create Date: 2026-03-31 13:50:44.032175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7226290fd8'
down_revision: Union[str, Sequence[str], None] = '20273ec1e1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=True)
    op.add_column('businesses', sa.Column('city_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.create_index(op.f('ix_businesses_city_id'), 'businesses', ['city_id'], unique=False)
    op.create_foreign_key(None, 'businesses', 'cities', ['city_id'], ['id'])
    op.drop_column('businesses', 'region')
    op.drop_column('businesses', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_index(op.f('ix_businesses_city_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.drop_column('businesses', 'city_id')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
