"""logo and banner image

Revision ID: 3d21f16c8407
Revises: e976411b3d57
Create Date: 2026-04-01 11:25:35.984057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d21f16c8407'
down_revision: Union[str, Sequence[str], None] = 'e976411b3d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.add_column('reviews', sa.Column('banner_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'banner_url')
    op.drop_column('reviews', 'logo_url')
    # ### end Alembic commands ###
